name: DiscordLink
version: 1.0
main: k5st1.DiscordLinkPlugin
api-version: 1.19.2
commands:
  dc:
    description: Wyświetla GUI dla połączenia z kontem Discord.
    usage: /dc
    permission: discordlink.use
permissions:
  discordlink.use:
    description: Uprawnienia do korzystania z komendy /dc
    default: true
